### ISSUE TITLE
Can It run on ASUS RT-AC86U with BCM4366c0?

### ISSUE THREAD

**Issue by bingwl** [seemoo-lab/mobisys2018_nexmon_software_defined_radio#22]
I would like to implement frame injection on a WiFi router, such as ASUS RT-AC86U with chip BCM4366c0. Well, does this patch suit for this chip?

**Comment by jlinktu** [comment]
You can use https://github.com/seemoo-lab/nexmon_tx_task to inject frames on the Asus RT-AC86U.
