### ISSUE TITLE
How to transmit the packet on 5 GHz band?

### ISSUE THREAD

**Issue by JianFB** [seemoo-lab/mobisys2018_nexmon_software_defined_radio#7]
Hi, I already can use the Raspberry Pi 3b+ to transmit the provided signal during the 2.4 GHz band. How can I make it on the 5 GHz band?  

Thanks.

**Comment by jlinktu** [comment]
Set the chanspec in generate_frame.m (line 125) to your needs...
You can find the 2 byte value corresponding to a channel by first setting your chip to a channel with nexutil (e.g. nexutil --chanspec=36/20) and then reading it out using nexutil -k
